name: decomp.dev report

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  packages: read
  id-token: write

jobs:
  report-sles-528-68:
    name: SLES_528.68 report
    runs-on: ubuntu-latest
    container: ghcr.io/braheezy/vjoe-build:main

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Git safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        
      - name: Build matching binary
        run: |
          python3 tools/scripts/configure_build.py
          ninja setup
          ninja

      - name: Generate objdiff report
        run: ninja report

      - name: Upload decomp.dev progress report
        uses: actions/upload-artifact@v4
        with:
          name: SLES_528.68_report
          path: build/SLES_528.68/report.json
          if-no-files-found: error
